import { type Metadata } from 'next'

import Header from '@/components/global/Header'
import LeftNavbar from '@/components/global/LeftNavbar'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
     <div>
        <Header varient='landing'/>
        <LeftNavbar/>
          {children}
     </div>
       
  )
}